name: Celebrare
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  double_back_to_close_app: ^2.1.0
  flutter_screenutil: ^5.9.0
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.2.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  fluttertoast: ^8.2.4
  intl: ^0.19.0
  carousel_slider: ^4.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # url_launcher: ^6.1.12
  flutter_svg:
  flutter_staggered_grid_view: ^0.6.1
  scroll_loop_auto_scroll: ^0.0.5
  video_player: ^2.7.2
  flutter_chat_bubble:
  google_fonts: ^6.1.0
  youtube_player_iframe: ^4.0.4
  # share: ^2.0.4
  flutter_carousel_widget: ^2.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/categories/
    - assets/reviews/
    - assets/profile_icons/
    - assets/grid-cards/
    - assets/bottombar/
    

 