//font map for font family functionality
final Map<String, List<String>> customizeFonts = {
  "lora_bold": ['Lora', '700'],
  "lora_bold_italic": ['Lora', '700', 'italic'],
  "lora_italic": ['Lora', '400', 'italic'],
  "lora_medium_italic": ['Lora', '500', 'italic'],
  "lora_semibold": ['Lora', '600'],
  "lora_semibold_italic": ['Lora', '600', 'italic'],
  "lora": ['Lora', '400'],
  "cinzel": ['Cinzel', '400'],
  "cinzel_bold": ['Cinzel', '700'],
  "spectral_sc": ['Spectral SC', '400'],
  "spectral_sc_bold": ['Spectral SC', '700'],
  "spectral_sc_light": ['Spectral SC', '300'],
  "petit_formal_script": ['Petit Formal Script', '400'],
  "pacifico": ['Pacifico', '400'],
  "cookie": ['Cookie', '400'],
  "merienda_one": ['Merienda', '400'],
  "kaushan_script": ['Kaushan Script', '400'],
  "marcellus_sc": ['Marcellus SC', '400'],
  "playfair_display_sc": ['Playfair Display SC', '400'],
  "bebas_neue": ['Bebas Neue', '400'],
  "lato": ['Lato', '400'],
  "lato_thin": ['Lato', '100'],
  "lato_italic": ['Lato', '400', 'italic'],
  "open_sans": ['Open Sans', '400'],
  "open_sans_semibold": ['Open Sans', '600'],
  "satisfy": ['Satisfy', '400'],
  "dancing_script": ['Dancing Script', '400'],
  "charm": ['Charm', '400'],
  "italianno": ['Italianno', '400'],
  "poppins_light": ['Poppins', '300'],
  "seaweed_script": ['Seaweed Script', '400'],
  "caveat": ['Caveat', '400'],
  "redressed": ['Redressed', '400'],
  "fondamento": ['Fondamento', '400'],
  "lobster_two": ['Lobster Two', '400'],
  "rouge_script": ['Rouge Script', '400'],
  "fjalla_one": ['Fjalla One', '400'],
  "handlee": ['Handlee', '400'],
  "droid_sans": ['Droid Sans', '400'],
  "indie_flower": ['Indie Flower', '400'],
  "kalam_light": ['Kalam', '300'],
  "roboto_thin": ['Roboto', '100'],
  "slabo": ['Slabo', '400'],
  "arial": ['Arial', '400'],
  "alegreya": ['Alegreya', '400'],
  "amethysta": ['Amethysta', '400'],
  "libre_baskerville": ['Libre Baskerville', '400'],
  "marck_script": ['Marck Script', '400'],
  "sacramento": ['Sacramento', '400'],
  "amita": ['Amita', '400'],
  "arya": ['Arya', '400'],
  "clicker_script": ['Clicker Script', '400'],
  "courgette": ['Courgette', '400'],
  "elsie": ['Elsie', '400'],
  "emilys_candy": ['Emilys Candy', '400'],
  "felipa": ['Felipa', '400'],
  "gotu": ['Gotu', '400'],
  "grand_hotel": ['Grand Hotel', '400'],
  "great_vibes": ['Great Vibes', '400'],
  "halant": ['Halant', '400'],
  "halant_mediumbold": ['Halant', '500'],
  "halant_semibold": ['Halant', '600'],
  "halant_bold": ['Halant', '700'],
  "kalam": ['Kalam', '400'],
  "norican": ['Norican', '400'],
  "niconne": ['Niconne', '400'],
  "oleo_script": ['Oleo Script', '400'],
  "oregano": ['Oregano', '400'],
  "playball": ['Playball', '400'],
  "quintessential": ['Quintessential', '400'],
  "ranga": ['Ranga', '400'],
  "rochester": ['Rochester', '400'],
  "sevillana": ['Sevillana', '400'],
  "sofia": ['Sofia', '400'],
  "tangerine": ['Tangerine', '400'],
  "roboto": ['Roboto', '400'],
  "cormorant_upright": ['Cormorant Upright', '400'],
  "देवनागरी": ['Tiro Devanagari Sanskrit', '400'],
  "अमिता": ['Amita', '400'],
  "गोटू": ['Gotu', '400'],
  "आर्य": ['Arya', '400'],
  "हलंत": ['Halant', '400'],
  "तिलाना": ['Tillana', '400']
};
